\cp /var/www/hec_fetch/temp/HEF.postgres.converted data_cache
\cp /var/www/hec_fetch/temp/SSN.postgres.converted data_cache
\cp /var/www/hec_fetch/temp/DSD.postgres.converted data_cache
\cp /var/www/hec_fetch/temp/SRS2.postgres.converted data_cache
\cp /var/www/hec_fetch/temp/SGS2.postgres.converted data_cache
\cp /var/www/hec_fetch/temp/KSO.postgres.converted data_cache
\cp /var/www/hec_fetch/temp/NPE.postgres.converted data_cache
\cp /var/www/hec_fetch/mssl_fetch/soho-2014_cme.txt data_cache
\cp /var/www/hec_fetch/mssl_fetch/soho-2014_flow.txt data_cache
\cp /var/www/hec_fetch/mssl_fetch/sta-2014_cme.txt data_cache
\cp /var/www/hec_fetch/mssl_fetch/sta-2014_flow.txt data_cache
\cp /var/www/hec_fetch/mssl_fetch/stb-2014_cme.txt data_cache
\cp /var/www/hec_fetch/mssl_fetch/stb-2014_flow.txt data_cache
\cp /var/www/hec_fetch/mssl_fetch/seeds_soho_2014.txt data_cache
\cp /var/www/hec_fetch/mssl_fetch/seeds_sta_2014.txt data_cache
\cp /var/www/hec_fetch/mssl_fetch/seeds_stb_2014.txt data_cache
\cp /var/www/hec_fetch/temp/GEVLOC_FLARES.postgres.converted data_cache
\cp /var/www/hec_fetch/temp/LCC.postgres.converted data_cache
\cp /var/www/hec_fetch/temp/LATEST_GEV_FLARE.postgres.converted data_cache
\cp /var/www/hec_fetch/mssl_fetch/gevloc1_list_201406z.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/soho_pm_shock.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/STEREO-A_shock.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/stereoa_het_sep.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/stereob_het_sep.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/sdemon_dimming.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/sdemon_flare.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/STEREO-B_shock.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/latest_gev_full.txt data_cache
\cp /var/www/hec_fetch/mssl_fetch/STEREO-A_icme.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/STEREO-A_icme.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/STEREO-B_icme.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/STEREO-B_icme.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/STEREO-A_sir.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/STEREO-B_sir.csv data_cache
\cp /var/www/hec_fetch/hfc_l3_t3_wind_waves.txt data_cache
\cp /var/www/hec_fetch/mssl_fetch/corimp_linear.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/corimp_quadratic.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/corimp_savgol.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/fermi_gbmflare.csv data_cache
\cp /var/www/hec_fetch/mssl_fetch/fermi_latevent.csv data_cache
