psql -d hec -c"alter table nmdb_gle_list rename time_start to baseline_start";
psql -d hec -c"alter table nmdb_gle_list rename time_end to baseline_end";
psql -d hec -c"alter table nmdb_gle_list rename time_onset to time_start";
wget -P /tmp "http://www.mssl.ucl.ac.uk/~rdb/helio-hec/nmdb_gle.csv";
wget -P /tmp "http://msslkz.mssl.ucl.ac.uk/usdownloads/helio_tmp/nmdb.sql";
psql -d hec -f /tmp/nmdb.sql;
psql -d hec -c"drop view noaa_active_region_summary";
psql -d hec -c"create view noaa_active_region_summary as SELECT srs_list.srs_id AS hec_id, srs_list.time_start, srs_list.nar, srs_list.latitude AS lat_hg, srs_list.longitude AS long_hg, srs_list.long_carr, srs_list.area, srs_list.zurich_class, srs_list.p_value, srs_list.c_value, srs_list.long_extent AS dlong_hg, srs_list.n_spots, srs_list.mag_class, srs_list.region_type, srs_list.solarmonitor_link from srs_list order by srs_id";
psql -d hec -c"grant all on noaa_active_region_summary to apache";
psql -d hec -c"update srs_list set solarmonitor_link='http://www.solarmonitor.org/region.php?date='||to_char(time_start,'YYYYMMDD')||'&region='||nar where longitude > 0;";
psql -d hec -c"create table hssws_cycle23(no int,flag varchar(3), time_start timestamp,time_end timestamp,bartels varchar(20),imf_polarity varchar(100),time_vmax timestamp,vmean int, vmax int, duration real,category varchar(30),source varchar(30))";
wget -P /tmp "http://msslkz.mssl.ucl.ac.uk/usdownloads/helio_tmp/hssws_catalogue.csv";
wget -P /tmp "http://msslkz.mssl.ucl.ac.uk/usdownloads/helio_tmp/hec_fillmetadata_cat.sql";
wget -P /tmp "http://msslkz.mssl.ucl.ac.uk/usdownloads/helio_tmp/hssws.sql";
psql -d hec -c"grant all on hssws_cycle23 to apache";
psql -d hec -f /tmp/hssws.sql;
psql -d hec -f /tmp/hec_fillmetadata_cat.sql;
