
package ws.clients.HEC;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HECService", targetNamespace = "http://dpas.helio.i4ds.ch/", wsdlLocation = "http://127.0.0.1:8080/core/services/hec?wsdl")
public class HECService
    extends Service
{

    private final static URL HECSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ws.clients.HEC.HECService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ws.clients.HEC.HECService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/core/services/hec?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/core/services/hec?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HECSERVICE_WSDL_LOCATION = url;
    }

    public HECService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HECService() {
        super(HECSERVICE_WSDL_LOCATION, new QName("http://dpas.helio.i4ds.ch/", "HECService"));
    }

    /**
     * 
     * @return
     *     returns HEC
     */
    @WebEndpoint(name = "HECPort")
    public HEC getHECPort() {
        return super.getPort(new QName("http://dpas.helio.i4ds.ch/", "HECPort"), HEC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HEC
     */
    @WebEndpoint(name = "HECPort")
    public HEC getHECPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dpas.helio.i4ds.ch/", "HECPort"), HEC.class, features);
    }

}
