
package ch.i4ds.helio.core;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FrontendFacade", targetNamespace = "http://core.helio.i4ds.ch/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FrontendFacade {


    /**
     * 
     * @param dateTo
     * @param instrument
     * @param dateFrom
     * @param maxResults
     * @return
     *     returns java.util.List<ch.i4ds.helio.core.ResultItem>
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "query_v1")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query_v1", targetNamespace = "http://core.helio.i4ds.ch/", className = "ch.i4ds.helio.core.QueryV1")
    @ResponseWrapper(localName = "query_v1Response", targetNamespace = "http://core.helio.i4ds.ch/", className = "ch.i4ds.helio.core.QueryV1Response")
    public List<ResultItem> queryV1(
        @WebParam(name = "instrument", targetNamespace = "")
        String instrument,
        @WebParam(name = "date_from", targetNamespace = "")
        String dateFrom,
        @WebParam(name = "date_to", targetNamespace = "")
        String dateTo,
        @WebParam(name = "max_results", targetNamespace = "")
        int maxResults)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "get_instruments_v1")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get_instruments_v1", targetNamespace = "http://core.helio.i4ds.ch/", className = "ch.i4ds.helio.core.GetInstrumentsV1")
    @ResponseWrapper(localName = "get_instruments_v1Response", targetNamespace = "http://core.helio.i4ds.ch/", className = "ch.i4ds.helio.core.GetInstrumentsV1Response")
    public List<String> getInstrumentsV1();

    /**
     * 
     * @param dateTo
     * @param dateFrom
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "run_initial_workflow")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "run_initial_workflow", targetNamespace = "http://core.helio.i4ds.ch/", className = "ch.i4ds.helio.core.RunInitialWorkflow")
    @ResponseWrapper(localName = "run_initial_workflowResponse", targetNamespace = "http://core.helio.i4ds.ch/", className = "ch.i4ds.helio.core.RunInitialWorkflowResponse")
    public String runInitialWorkflow(
        @WebParam(name = "date_from", targetNamespace = "")
        String dateFrom,
        @WebParam(name = "date_to", targetNamespace = "")
        String dateTo)
        throws Exception_Exception
    ;

}
