wget -P /tmp "http://www.mssl.ucl.ac.uk/~rdb/helio-hec/wind_typeii_soho_cme.csv";
wget -P /tmp "http://www.mssl.ucl.ac.uk/~rdb/helio-hec/corimp_savgol.csv";
wget -P /tmp "http://www.mssl.ucl.ac.uk/~rdb/helio-hec/corimp_quadratic.csv";
wget -P /tmp "http://www.mssl.ucl.ac.uk/~rdb/helio-hec/corimp_linear.csv";
wget -P /tmp "http://www.mssl.ucl.ac.uk/~rdb/helio-hec/fermi_latevent.csv";
wget -P /tmp "http://www.mssl.ucl.ac.uk/~rdb/helio-hec/fermi_gbmflare.csv";
wget -P /tmp "http://www.mssl.ucl.ac.uk/~rdb/helio-hec/fermi_gbmflare_base.csv";
wget -P /tmp "http://www.mssl.ucl.ac.uk/~rdb/helio-hec/richardson_sep.csv";
wget -P /tmp "http://www.mssl.ucl.ac.uk/~rdb/helio-hec/wind_stereo_ii_iv_radioburst.csv";
psql -d hec -c"create table corimp_soho_savgol(time_start timestamp,pa integer,pa_width integer,v_median integer, v_max integer, accel_median integer, accel_max integer, accel_min integer, mass real,url_kins varchar(200),url_mass varchar(200), url_c2movie varchar(200), url_c3movie varchar(200))";
psql -d hec -c"create table corimp_soho_quadratic(time_start timestamp,pa integer,pa_width integer,v_median integer, v_max integer, accel_median integer, accel_max integer, accel_min integer, mass real,url_kins varchar(200),url_mass varchar(200), url_c2movie varchar(200), url_c3movie varchar(200))";
psql -d hec -c"create table corimp_soho_linear(time_start timestamp,pa integer,pa_width integer,v_median integer, v_max integer, accel_median integer, accel_max integer, accel_min integer, mass real,url_kins varchar(200),url_mass varchar(200), url_c2movie varchar(200), url_c3movie varchar(200))";
psql -d hec -c"create table fermi_lat_event(time_start timestamp,time_end timestamp,flux double precision,n_sigma real)";
psql -d hec -c"create table fermi_gbm_flare(gbm_id varchar(50),time_start timestamp,time_peak timestamp,time_end timestamp,duration integer,rate_peak integer, total integer, detectors varchar(50), trigger varchar(50), rhessi_id varchar(50))";
psql -d hec -c"create table energetic_sep_multipoint(time_start timestamp,time_onset_sep timestamp,long_hg_stb integer, int_stb real, long_hg_soho integer, int_soho real, long_hg_sta integer, int_sta real, xray_class varchar(50), type_3 integer, type_2 integer, pa_width integer, v integer, comment varchar(300))";
psql -d hec -c"grant all on fermi_lat_event to apache";
psql -d hec -c"grant all on corimp_soho_savgol to apache";
psql -d hec -c"grant all on corimp_soho_quadratic to apache";
psql -d hec -c"grant all on corimp_soho_linear to apache";
psql -d hec -c"grant all on fermi_gbm_flare to apache";
psql -d hec -c"grant all on energetic_sep_multipoint to apache";
psql -d hec -c"DELETE FROM wind_typeii_soho_cme;";
psql -d hec -c"COPY wind_typeii_soho_cme (time_start,time_end,freq_start,freq_end,lat_hg,long_hg,long_carr,loc,nar,filar,xray_class,time_cme,pa,pa_width_ll,pa_width,v_ps,comment) FROM '/tmp/wind_typeii_soho_cme.csv' with delimiter '|' csv header;";
psql -d hec -c"DELETE FROM waves_exp_wind_stereo;";
psql -d hec -c"COPY waves_exp_wind_stereo(identifier,time_start,time_end,freq_start,freq_end,dyn_spec,rem) FROM '/tmp/wind_stereo_ii_iv_radioburst.csv' with delimiter '|' csv header;";
psql -d hec -c"update srs_list set solarmonitor_link='http://www.solarmonitor.org/region.php?date='||to_char(time_start,'YYYYMMDD')||'&region='||nar where longitude >= -90;";
